export enum FormSelectors {
  ADDRESS_TEXTAREA = 'div textarea',
  BIRTHDAY_INPUT = 'div input#dateOfBirthInput',
  CITY_INPUT = 'div#city',
  DATEPICKER_DAY_CELL = 'div.react-datepicker__day:not(.react-datepicker__day--outside-month)',
  DATEPICKER_MONTH_SELECT = 'select.react-datepicker__month-select',
  DATEPICKER_YEAR_SELECT = 'select.react-datepicker__year-select',
  EMAIL_INPUT = 'div input[placeholder="name@example.com"]',
  FILE_UPLOAD = 'div input[type="file"]',
  FIRST_NAME_INPUT = 'div input[placeholder="First Name"]',
  GENDER_RADIO_BUTTONS = 'div label',
  HOBBY_CHECKBOXES = 'div label',
  INPUTS = 'div input',
  LAST_NAME_INPUT = 'div input[placeholder="Last Name"]',
  MAIN_HEADER = 'div h1',
  MODAL = 'div.modal-content',
  MODAL_CLOSE_BUTTON = 'div.modal-footer #closeLargeModal',
  MODAL_HEADER = 'div.modal-header',
  MODAL_TABLE_CELLS = 'div.modal-body tbody tr td',
  MODAL_TABLE_ROWS = 'div.modal-body tbody tr',
  PHONE_NUMBER_INPUT = 'div input[placeholder="Mobile Number"]',
  STATE_INPUT = 'div#state',
  STATE_MENU = 'div[class*="menu"]',
  SUBJECTS_INPUT = 'div input#subjectsInput',
  SUBJECTS_MENU = 'div[class="subjects-auto-complete__menu"]',
  SUBMIT_BUTTON = 'div button#submit'
}